- src/session/fd.c
- src/wlc.c
See: POS36-C. Observe correct revocation order while relinquishing privileges
> Fix order in which privileges are dropped

- CMake/FindWayland.cmake
- README.rst
Without this explicit failure, CMake goes through fine, but we get a
cryptic compilation error during `make`.
Background: I'm on Gentoo and the current stable wayland version is 1.6.1. It took me a while to figure out why wlc wouldn't compile.
> Make CMake fail if wayland is not recent enough

- src/platform/backend/x11.c
Since we use xcb calls I changed to XCB_ATOM_*. Window name now showing correctly in the window frame and with wmctrl -l.
> Fixed window naming in X11 backend

- src/compositor/output.c
The current wlc version does not set the 'WL_OUTPUT_MODE_CURRENT' flag for any mode of my second screen which causes some trouble with sway.
Please have a look if my changes make sense (you can only have one current mode I guess), it solves my issues with sway.
> Set OUTPUT_MODE_CURRENT flag for the active mode

- src/wlc.c
In sway if you have an xwayland window open eg a terminal and then exit
sway without closing this terminal, wlc crashes and leaves sock files
behind
> Close xwayland before the compositor

- src/compositor/seat/seat.c
- src/compositor/seat/touch.c
- src/session/udev.c
NOTE: This does not get touch working. Only MOTION and DOWN events are
sent to a client. This is because wlc_touch_touch tries to find the
underlying view via view_under_touch which fails for UP, FRAME, CANCEL since
they do not send the pos, so we return before
wl_touch_send_up,frame,cancel can be called.
> Fix touchscreen crashes

- src/compositor/seat/keyboard.c
- src/compositor/seat/seat.c
Makes sure that key combos/wm commands grapped by the compositor is
repeated by wlc.
> Fix repeat keys for WM commands.

- README.rst
We have some Rust bindings around ~97% of wlc (excluding xkb bindings, libinput) and just updated to the latest version.
The link (in the commit) is https://github.com/Immington-Industries/rust-wlc.
> Add link to rust bindings

- src/compositor/view.c
This should make it possible to defocus all views by passing 0 to `wlc_view_focus()`
Note this will also defocus views if an invalid wlc_handle != 0 is passed, but I guess that is fine since you shouldn't pass an invalid handle in the first place?
Fix #132
> Fix defocusing views

- src/compositor/compositor.c
- src/compositor/output.c
- src/compositor/seat/pointer.c
- src/compositor/seat/pointer.h
- src/compositor/seat/seat.c
- src/compositor/view.c
- src/resources/types/surface.c
- src/resources/types/surface.h
Should resolve #22 
This is my work on subsurfaces inside WLC. I haven't tested them a lot(the only compositor tested is orbment), but gedit and nautlilus work properly now(and they use subsurfaces). If there is anything which doesn't work, please tell me, I'll do my best to fix it.
What this pull request does is rendering the subsurfaces of a surface and also modify pointer focus functions to support focusing of subsurfaces. 
Things that still need to be done(aka TODO list):
1. Implement proper handling of synchronized subsurfaces - DONE
2. Implement subsurface::place_above and subsurface::place_below - DONE, but untested
> Implement subsurfaces

- include/wlc/wlc-render.h
- include/wlc/wlc-wayland.h
- src/extended/wlc-render.c
- src/extended/wlc-wayland.c
- src/platform/render/gles2.c
- src/platform/render/render.h
- src/resources/types/surface.h
This allows compositors to draw surfaces the way they want to,
so that they can also create custom animations.
New functions:
wlc_output_get_renderer()
wlc_surface_get_textures()
wlc_surface_get_subsurfaces()
wlc_get_subsurface_geometry()
wlc_surface_flush_frame_callbacks()
Maybe resolves #8 ?
> Implement functions to get surface textures

- src/extended/wlc-render.c
I'm opening another pull request because from what I read there is no way to update the previous one. This is just the changes we discussed.
Proposed changes make it possible to move/resize the view even when its mask is 0
> Commit view while flushing callbacks

- include/wlc/wlc.h
- src/compositor/compositor.c
- src/compositor/output.c
- src/compositor/output.h
- src/compositor/seat/seat.c
- src/platform/context/egl.c
- src/wlc.c
From what I saw, there is currently no signal which is emitted when the current tty is changed. When such a thing happens, the GL context is destroyed. This causes problems when the compositor has own GL state(textures, programs etc.) because these have to be recreated also. That's why we need the activated/deactivated signals. There is also a fix for switching to a tty >= 12. Lastly, why are alpha and depth buffers disabled? These are useful for creating a fade-in/out animation, as well as when rendering 3D animations.
Resolves #137
> Implement new callbacks and several *fixes*

- src/platform/backend/drm.c
I have the case, that a lot of modes are duplicated, which I assume is related to different refresh rates. Therefore it makes sense to log this information as well.
> Log mode refresh rates as well

- src/wlc.c
This makes it easier to run the compositors for people not using ck/logind or anything else setting XDG_RUNTIME_DIR
> Use a fallback XDG_RUNTIME_DIR, when applicable

- README.rst
We've been writing a compositor, [Way Cooler](https://github.com/Immington-Industries/way-cooler), using our listed [Rust bindings](https://github.com/Immington-Industries/rust-wlc). Just posted about it on Reddit yesterday, would be nice to get mentioned in wlc, it's been very helpful for us.
> Include way-cooler in README

- src/xwayland/xwm.c
Some, or maybe even all X11 windows are having trouble when wlc_set_view_request_geometry_cb callback accepts geometry they requested, as this geometry is then send back with incorrect border size set. This cases affected X11 windows to slowly, uncontrollably and indefinitely grow.
> Fix: Inform X11 windows about border size. Fixes #191

- src/platform/render/gles2.c
Flips vertical coordinates in `read_pixels` so we can pass a "regular" `wlc_geometry` struct without having to adjust it for OpenGL coordinates.
> flip vertical coordinates in read_pixels()

- src/session/fd.c
- src/xwayland/xwayland.c
Abstract sockets and capabilities are Linux only.
> Fix XWayland and security on FreeBSD

- include/wlc/wlc.h
- src/compositor/output.c
- src/compositor/output.h
- src/platform/backend/backend.h
- src/platform/backend/drm.c
Closes https://github.com/Cloudef/wlc/issues/174
> Add gamma control API

- src/session/fd.c
- src/session/logind.c
- src/session/tty.c
sys/sysmacros.h implicit inclusion is being deprecated (even with _DEFAULT_SOURCE), so it would cause build breakage on future updates.
See https://bugs.gentoo.org/show_bug.cgi?id=604608 and https://sourceware.org/ml/libc-alpha/2015-11/msg00253.html (also mentioned in glibc news)
> Include sys/sysmacros.h for major/minor(3) (Linux)

- src/xwayland/xwm.c
Usually the second part of WM_CLASS (the actual window class, not the instance) is
expected (compare to i3wm class property) so we use this one.
This fixes #218
> Use WM_CLASS class instead of instance (fix #218)

- example/example.c
- include/wlc/wlc.h
- src/CMakeLists.txt
- src/compositor/shell/xdg-shell.c
- src/compositor/shell/xdg-shell.h
- src/compositor/view.c
- src/resources/types/xdg-popup.h
- src/resources/types/xdg-positioner.c
- src/resources/types/xdg-positioner.h
Nobody protested, so here is promised PR :)
Basically, this does as we discussed in #210. It's squashed, with redundant `wlc_popup_get_parent` method omitted and includes change to example.c that shows how popup-menu can be correctly positioned and ignored in tiling.
> Implemented xdg-positioner

- include/wlc/wlc.h
- src/compositor/view.c
- src/compositor/view.h
- src/xwayland/xwm.c
Added `wlc_view_get_instance()` as requested by @SirCmpwn in https://github.com/Cloudef/wlc/pull/222 so we can have old functionality back again, it's pretty much analogous to `wlc_view_get_class()`.
I hope I didn't miss anything.
> Feature: add wlc_view_get_instance()

- src/platform/backend/backend.h
- src/platform/backend/drm.c
- src/platform/backend/x11.c
- src/platform/context/egl.c
eglGetDisplay does not know what sort of handle it is getting passed
in (a gbm device handle or an X11 display pointer) on systems without
glvnd some poking into internal X11 / gbm structures is used to figure
this out, which is somewhat dangerous but works.
On system using glvnd this does not work and eglGetDisplay returns NULL.
This commit makes wlc track the EGLNativeDisplayType pointer's
underlying type and uses eglGetPlatformDisplayEXT where available so
that the EGL implementation does not need to guess the type of the
handle it is being passed.
BugLink: https://bugzilla.redhat.com/show_bug.cgi?id=1413579
Signed-off-by: Hans de Goede <hdegoede@redhat.com>
> wlc: Use eglGetPlatformDisplayEXT where available

- src/resources/types/xdg-positioner.c
Hello,
I've noticed I made mistake in my recent PR. For xdg-positioners with gravity set, value is placed over value for anchor. Those values are defined basically the same, so it doesn't cause crash or anything, but retrieving anchor or gravity values later may return nonsense.
> Fix: Calling wlc_xdg_positioner_protocol_set_gravity actually sets anchor

- example/example.c
The rationale is that if you use special control key combinations, underlying window will actually get key release event, which is wrong
> Fixed bug related to the BUTTON_STATE_PRESSED

- README.rst
- src/compositor/output.h
- src/platform/backend/backend.h
- src/platform/backend/drm.c
- src/platform/context/egl.c
- src/platform/context/egl.h
Add support for EGL streams used by the proprietary NVIDIA driver: #138
The current implementation selects the EGL stream buffer API (instead of the default GBM one) when the `WLC_USE_EGLDEVICE` environment variable is not empty (e.g.: `export WLC_USE_EGLDEVICE=1` is needed at runtime).
I've only tested it by running the `example` compositor on a single monitor setup (Archlinux using latest NVIDIA drivers) and it seems to work.
Disclaimer: I don't know `C`, so most probably the code contains lots of bugs so please review very carefully (especially around memory allocations/deallocations).
> Add EGL stream support

- README.rst
- src/platform/backend/drm.c
Implement buffer API auto-detection as discussed in #247 
For the auto-detection logic I've used the `drmGetVersion` function which seems to return the driver used by the DRM device.
> Implement buffer API autodetection

- src/session/tty.c
Note: this may cause conflicts with #194
> Fix typos in tty.c log messages

- src/compositor/view.c
wlc_view_set_parent tries to convert parent view into 'parent' type, which is nowhere to be found.
Fixing it to `convert_from_wlc_handle(parent, "view")` seems to work as expected.
> Fix: Typo in wlc_view_set_parent

- src/compositor/seat/seat.c
- src/compositor/seat/touch.c
- src/compositor/seat/touch.h
As I've described in #266, wlc currently reports touch events with view set to one over which mouse cursor is hovering.
With this PR, touch would remember view that was touched initially, so touch down event and subsequent touch events are reported for that view.
> Change way how view paramater in touch event is computed

- example/example.c
- include/wlc/wlc.h
- src/compositor/seat/data.c
- src/compositor/seat/data.h
- src/internal.h
- src/resources/types/data-source.c
- src/resources/types/data-source.h
- src/wlc.c
These changes make custom data-source implementations possible.
Required for x11/wayland clipboard sync and e.g. a cli (or non-wayland protocol) to set the compositors clipboard. See the first commit for more details.
> Polymorphic data-sources

- src/xwayland/selection.c
This fixes another problem i ran into when debugging images in the clipboard (would really like to finish this feature...).
This patch fixes supported for general mime types; images on the clipboard will work now (works with gnomes epiphany browser and gimp as you described). It does still not work for qutebrowser but this is pretty sure a bug in qt/qutebrowser. It does not work in gnome either, the problem is that qutebrowser does only offer the x-qt-image mime type under wayland which is not supported by gimp (it does not offer the image/{png,jpg,..} mime types as it does under x11).
Not sure if this is a known bug, i personlly don't use qutebrowser but it might be worth a bug report after some research.
Try it out by e.g. logging the supported types received in the compositor directly …
> Xwayland selection fix

- src/compositor/seat/data.c
- src/compositor/seat/data.h
- src/compositor/seat/seat.c
This fixes a data.c bug. Currently, it does not send notifications to the focused client when a selection changes which results in a segmentation fault if the clients tries then to receive from the (no longer valid) data offer. Usually clients don't use the wayland protocol when they want to access their own data source but manage it internally which is why this did not introduce any real problems until now, but would e.g. when implementing Sircmpwn/sway#926 (since then the source is changed without that the client can know it).
> Notify focused client on changed selection

- example/example.c
- include/wlc/wlc.h
- src/compositor/compositor.c
- src/compositor/seat/data.c
- src/wlc.c
- src/xwayland/selection.c
- src/xwayland/xwm.h
This enables compositors using wlc to receive the supported mime types of the current selection and then request the data in a certain format. It also shows the usage in the example compositor, currently using the ctrl+comma shurtcut to output the current text data selection (there might be something better for this, didn't want to use ctrl+v since this is usually used by applications, not sure if it matters in this case).
It also fixes various smaller issues, see the second commit messag for details.
The public wlc api was designed to offer the greatest possible freedom, which makes it a bit harder to use  (see the example, one has to call pipe2 in the compositor and add a wlc event source).
Could be used to (fully) fix SirCmpwn/sway#926.
> Public api to receive clipboard data

- include/wlc/defines.h
- include/wlc/wlc.h
- src/compositor/compositor.c
- src/compositor/seat/seat.c
- src/internal.h
This fixes #181 by adding an interface where we use doubles instead of integers, so we don't accidentally round down and lose small motions.
Tested against https://github.com/ascent12/sway/commit/c29e5bbde84260763eaece5b47c219fd1fff7883
> Added v2 pointer motion interface

- src/xwayland/selection.c
In case xwayland terminates before compositor activated, xwm selection listener link is invalid. This causes crash in `wlc_xwm_selection_release`.
Fixed as in `wlc_pointer_release` with notification callback check.
> Fix xwm selection release

- src/compositor/seat/data.c
- src/resources/types/data-source.h
This among other things allows SDL to work on wlc, since it requires version 3. Wlc only provided version 2 before this.
Some useless stuff is done in the set_actions functions currently, but this useless stuff could potentially be expanded into a functioning dnd system.
> Add drag and drop stub

- src/compositor/output.c
Similar fix as [this issue in wlroots](https://github.com/swaywm/wlroots/issues/535)
I don't know this codebase very well, so this might not be the most correct place to fix it. I saw a similar structure to how it works in wlroots and it seems to work on my local copy.
> Don't send mode info twice on DRM refresh
